# Generated by Django 4.2 on 2023-05-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="blog.tag"),
        ),
    ]
