# Generated by Django 4.2 on 2023-05-03 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
