# Generated by Django 4.2 on 2023-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_country_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="email_address",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(related_name="books", to="book.country"),
        ),
    ]
