# Generated by Django 4.2 on 2023-05-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                upload_to="user_profile", verbose_name="Profile Picture"
            ),
        ),
    ]
